/* Automatically @generated by tree-sitter v0.25.8 */

#include "tree_sitter/parser.h"

#if defined(__GNUC__) || defined(__clang__)
#pragma GCC diagnostic ignored "-Wmissing-field-initializers"
#endif

#define LANGUAGE_VERSION 15
#define STATE_COUNT 116
#define LARGE_STATE_COUNT 2
#define SYMBOL_COUNT 58
#define ALIAS_COUNT 1
#define TOKEN_COUNT 29
#define EXTERNAL_TOKEN_COUNT 7
#define FIELD_COUNT 0
#define MAX_ALIAS_SEQUENCE_LENGTH 4
#define MAX_RESERVED_WORD_SET_SIZE 0
#define PRODUCTION_ID_COUNT 2
#define SUPERTYPE_COUNT 0

enum ts_symbol_identifiers {
  anon_sym_LT = 1,
  anon_sym_GT = 2,
  anon_sym_template = 3,
  anon_sym_slot = 4,
  anon_sym_block = 5,
  anon_sym_wxs = 6,
  anon_sym_SLASH_GT = 7,
  anon_sym_LT_SLASH = 8,
  anon_sym_EQ = 9,
  sym_attribute_name = 10,
  sym_attribute_value = 11,
  sym_entity = 12,
  anon_sym_SQUOTE = 13,
  aux_sym_quoted_attribute_value_token1 = 14,
  anon_sym_DQUOTE = 15,
  aux_sym_quoted_attribute_value_token2 = 16,
  sym_text = 17,
  aux_sym__interpolation_text_token1 = 18,
  anon_sym_LBRACE = 19,
  anon_sym_RBRACE = 20,
  anon_sym_import = 21,
  anon_sym_include = 22,
  sym__start_tag_name = 23,
  sym__end_tag_name = 24,
  sym_raw_text = 25,
  sym_comment = 26,
  sym__interpolation_start = 27,
  sym__interpolation_end = 28,
  sym_document = 29,
  sym__node = 30,
  sym_element = 31,
  sym_start_tag = 32,
  sym_self_closing_tag = 33,
  sym_end_tag = 34,
  sym_attribute = 35,
  sym_quoted_attribute_value = 36,
  sym_interpolation = 37,
  aux_sym__interpolation_text = 38,
  sym__js_brace_expression = 39,
  sym_import_statement = 40,
  sym_include_statement = 41,
  sym_template_element = 42,
  sym_template_start_tag = 43,
  sym_template_end_tag = 44,
  sym_slot_element = 45,
  sym_slot_start_tag = 46,
  sym_slot_end_tag = 47,
  sym_block_element = 48,
  sym_wxs_element = 49,
  sym_block_start_tag = 50,
  sym_block_end_tag = 51,
  sym_wxs_start_tag = 52,
  sym_wxs_end_tag = 53,
  aux_sym_document_repeat1 = 54,
  aux_sym_start_tag_repeat1 = 55,
  aux_sym_quoted_attribute_value_repeat1 = 56,
  aux_sym_quoted_attribute_value_repeat2 = 57,
  alias_sym_expression = 58,
};

static const char * const ts_symbol_names[] = {
  [ts_builtin_sym_end] = "end",
  [anon_sym_LT] = "<",
  [anon_sym_GT] = ">",
  [anon_sym_template] = "tag_name",
  [anon_sym_slot] = "tag_name",
  [anon_sym_block] = "tag_name",
  [anon_sym_wxs] = "tag_name",
  [anon_sym_SLASH_GT] = "/>",
  [anon_sym_LT_SLASH] = "</",
  [anon_sym_EQ] = "=",
  [sym_attribute_name] = "attribute_name",
  [sym_attribute_value] = "attribute_value",
  [sym_entity] = "entity",
  [anon_sym_SQUOTE] = "'",
  [aux_sym_quoted_attribute_value_token1] = "quoted_attribute_value_token1",
  [anon_sym_DQUOTE] = "\"",
  [aux_sym_quoted_attribute_value_token2] = "quoted_attribute_value_token2",
  [sym_text] = "text",
  [aux_sym__interpolation_text_token1] = "_interpolation_text_token1",
  [anon_sym_LBRACE] = "{",
  [anon_sym_RBRACE] = "}",
  [anon_sym_import] = "tag_name",
  [anon_sym_include] = "tag_name",
  [sym__start_tag_name] = "tag_name",
  [sym__end_tag_name] = "tag_name",
  [sym_raw_text] = "raw_text",
  [sym_comment] = "comment",
  [sym__interpolation_start] = "interpolation_start",
  [sym__interpolation_end] = "interpolation_end",
  [sym_document] = "document",
  [sym__node] = "_node",
  [sym_element] = "element",
  [sym_start_tag] = "start_tag",
  [sym_self_closing_tag] = "self_closing_tag",
  [sym_end_tag] = "end_tag",
  [sym_attribute] = "attribute",
  [sym_quoted_attribute_value] = "quoted_attribute_value",
  [sym_interpolation] = "interpolation",
  [aux_sym__interpolation_text] = "_interpolation_text",
  [sym__js_brace_expression] = "_js_brace_expression",
  [sym_import_statement] = "import_statement",
  [sym_include_statement] = "include_statement",
  [sym_template_element] = "template_element",
  [sym_template_start_tag] = "template_start_tag",
  [sym_template_end_tag] = "template_end_tag",
  [sym_slot_element] = "slot_element",
  [sym_slot_start_tag] = "slot_start_tag",
  [sym_slot_end_tag] = "slot_end_tag",
  [sym_block_element] = "block_element",
  [sym_wxs_element] = "wxs_element",
  [sym_block_start_tag] = "block_start_tag",
  [sym_block_end_tag] = "block_end_tag",
  [sym_wxs_start_tag] = "wxs_start_tag",
  [sym_wxs_end_tag] = "wxs_end_tag",
  [aux_sym_document_repeat1] = "document_repeat1",
  [aux_sym_start_tag_repeat1] = "start_tag_repeat1",
  [aux_sym_quoted_attribute_value_repeat1] = "quoted_attribute_value_repeat1",
  [aux_sym_quoted_attribute_value_repeat2] = "quoted_attribute_value_repeat2",
  [alias_sym_expression] = "expression",
};

static const TSSymbol ts_symbol_map[] = {
  [ts_builtin_sym_end] = ts_builtin_sym_end,
  [anon_sym_LT] = anon_sym_LT,
  [anon_sym_GT] = anon_sym_GT,
  [anon_sym_template] = sym__start_tag_name,
  [anon_sym_slot] = sym__start_tag_name,
  [anon_sym_block] = sym__start_tag_name,
  [anon_sym_wxs] = sym__start_tag_name,
  [anon_sym_SLASH_GT] = anon_sym_SLASH_GT,
  [anon_sym_LT_SLASH] = anon_sym_LT_SLASH,
  [anon_sym_EQ] = anon_sym_EQ,
  [sym_attribute_name] = sym_attribute_name,
  [sym_attribute_value] = sym_attribute_value,
  [sym_entity] = sym_entity,
  [anon_sym_SQUOTE] = anon_sym_SQUOTE,
  [aux_sym_quoted_attribute_value_token1] = aux_sym_quoted_attribute_value_token1,
  [anon_sym_DQUOTE] = anon_sym_DQUOTE,
  [aux_sym_quoted_attribute_value_token2] = aux_sym_quoted_attribute_value_token2,
  [sym_text] = sym_text,
  [aux_sym__interpolation_text_token1] = aux_sym__interpolation_text_token1,
  [anon_sym_LBRACE] = anon_sym_LBRACE,
  [anon_sym_RBRACE] = anon_sym_RBRACE,
  [anon_sym_import] = sym__start_tag_name,
  [anon_sym_include] = sym__start_tag_name,
  [sym__start_tag_name] = sym__start_tag_name,
  [sym__end_tag_name] = sym__start_tag_name,
  [sym_raw_text] = sym_raw_text,
  [sym_comment] = sym_comment,
  [sym__interpolation_start] = sym__interpolation_start,
  [sym__interpolation_end] = sym__interpolation_end,
  [sym_document] = sym_document,
  [sym__node] = sym__node,
  [sym_element] = sym_element,
  [sym_start_tag] = sym_start_tag,
  [sym_self_closing_tag] = sym_self_closing_tag,
  [sym_end_tag] = sym_end_tag,
  [sym_attribute] = sym_attribute,
  [sym_quoted_attribute_value] = sym_quoted_attribute_value,
  [sym_interpolation] = sym_interpolation,
  [aux_sym__interpolation_text] = aux_sym__interpolation_text,
  [sym__js_brace_expression] = sym__js_brace_expression,
  [sym_import_statement] = sym_import_statement,
  [sym_include_statement] = sym_include_statement,
  [sym_template_element] = sym_template_element,
  [sym_template_start_tag] = sym_template_start_tag,
  [sym_template_end_tag] = sym_template_end_tag,
  [sym_slot_element] = sym_slot_element,
  [sym_slot_start_tag] = sym_slot_start_tag,
  [sym_slot_end_tag] = sym_slot_end_tag,
  [sym_block_element] = sym_block_element,
  [sym_wxs_element] = sym_wxs_element,
  [sym_block_start_tag] = sym_block_start_tag,
  [sym_block_end_tag] = sym_block_end_tag,
  [sym_wxs_start_tag] = sym_wxs_start_tag,
  [sym_wxs_end_tag] = sym_wxs_end_tag,
  [aux_sym_document_repeat1] = aux_sym_document_repeat1,
  [aux_sym_start_tag_repeat1] = aux_sym_start_tag_repeat1,
  [aux_sym_quoted_attribute_value_repeat1] = aux_sym_quoted_attribute_value_repeat1,
  [aux_sym_quoted_attribute_value_repeat2] = aux_sym_quoted_attribute_value_repeat2,
  [alias_sym_expression] = alias_sym_expression,
};

static const TSSymbolMetadata ts_symbol_metadata[] = {
  [ts_builtin_sym_end] = {
    .visible = false,
    .named = true,
  },
  [anon_sym_LT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_template] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_slot] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_block] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_wxs] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SLASH_GT] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_LT_SLASH] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_EQ] = {
    .visible = true,
    .named = false,
  },
  [sym_attribute_name] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_entity] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_SQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_DQUOTE] = {
    .visible = true,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_token2] = {
    .visible = false,
    .named = false,
  },
  [sym_text] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__interpolation_text_token1] = {
    .visible = false,
    .named = false,
  },
  [anon_sym_LBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_RBRACE] = {
    .visible = true,
    .named = false,
  },
  [anon_sym_import] = {
    .visible = true,
    .named = true,
  },
  [anon_sym_include] = {
    .visible = true,
    .named = true,
  },
  [sym__start_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym__end_tag_name] = {
    .visible = true,
    .named = true,
  },
  [sym_raw_text] = {
    .visible = true,
    .named = true,
  },
  [sym_comment] = {
    .visible = true,
    .named = true,
  },
  [sym__interpolation_start] = {
    .visible = true,
    .named = true,
  },
  [sym__interpolation_end] = {
    .visible = true,
    .named = true,
  },
  [sym_document] = {
    .visible = true,
    .named = true,
  },
  [sym__node] = {
    .visible = false,
    .named = true,
  },
  [sym_element] = {
    .visible = true,
    .named = true,
  },
  [sym_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_self_closing_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_attribute] = {
    .visible = true,
    .named = true,
  },
  [sym_quoted_attribute_value] = {
    .visible = true,
    .named = true,
  },
  [sym_interpolation] = {
    .visible = true,
    .named = true,
  },
  [aux_sym__interpolation_text] = {
    .visible = false,
    .named = false,
  },
  [sym__js_brace_expression] = {
    .visible = false,
    .named = true,
  },
  [sym_import_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_include_statement] = {
    .visible = true,
    .named = true,
  },
  [sym_template_element] = {
    .visible = true,
    .named = true,
  },
  [sym_template_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_template_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_slot_element] = {
    .visible = true,
    .named = true,
  },
  [sym_slot_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_slot_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_block_element] = {
    .visible = true,
    .named = true,
  },
  [sym_wxs_element] = {
    .visible = true,
    .named = true,
  },
  [sym_block_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_block_end_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_wxs_start_tag] = {
    .visible = true,
    .named = true,
  },
  [sym_wxs_end_tag] = {
    .visible = true,
    .named = true,
  },
  [aux_sym_document_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_start_tag_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_repeat1] = {
    .visible = false,
    .named = false,
  },
  [aux_sym_quoted_attribute_value_repeat2] = {
    .visible = false,
    .named = false,
  },
  [alias_sym_expression] = {
    .visible = true,
    .named = true,
  },
};

static const TSSymbol ts_alias_sequences[PRODUCTION_ID_COUNT][MAX_ALIAS_SEQUENCE_LENGTH] = {
  [0] = {0},
  [1] = {
    [1] = alias_sym_expression,
  },
};

static const uint16_t ts_non_terminal_alias_map[] = {
  aux_sym__interpolation_text, 2,
    aux_sym__interpolation_text,
    alias_sym_expression,
  0,
};

static const TSStateId ts_primary_state_ids[STATE_COUNT] = {
  [0] = 0,
  [1] = 1,
  [2] = 2,
  [3] = 3,
  [4] = 4,
  [5] = 5,
  [6] = 6,
  [7] = 7,
  [8] = 8,
  [9] = 9,
  [10] = 10,
  [11] = 11,
  [12] = 12,
  [13] = 12,
  [14] = 14,
  [15] = 15,
  [16] = 16,
  [17] = 12,
  [18] = 18,
  [19] = 19,
  [20] = 19,
  [21] = 15,
  [22] = 16,
  [23] = 18,
  [24] = 15,
  [25] = 12,
  [26] = 15,
  [27] = 12,
  [28] = 15,
  [29] = 29,
  [30] = 30,
  [31] = 31,
  [32] = 32,
  [33] = 33,
  [34] = 34,
  [35] = 35,
  [36] = 36,
  [37] = 37,
  [38] = 38,
  [39] = 39,
  [40] = 40,
  [41] = 41,
  [42] = 42,
  [43] = 43,
  [44] = 44,
  [45] = 45,
  [46] = 46,
  [47] = 47,
  [48] = 48,
  [49] = 49,
  [50] = 50,
  [51] = 51,
  [52] = 52,
  [53] = 53,
  [54] = 54,
  [55] = 55,
  [56] = 56,
  [57] = 57,
  [58] = 58,
  [59] = 59,
  [60] = 60,
  [61] = 61,
  [62] = 62,
  [63] = 63,
  [64] = 64,
  [65] = 65,
  [66] = 66,
  [67] = 67,
  [68] = 68,
  [69] = 69,
  [70] = 70,
  [71] = 71,
  [72] = 72,
  [73] = 73,
  [74] = 74,
  [75] = 75,
  [76] = 76,
  [77] = 77,
  [78] = 57,
  [79] = 79,
  [80] = 80,
  [81] = 81,
  [82] = 82,
  [83] = 52,
  [84] = 84,
  [85] = 57,
  [86] = 86,
  [87] = 87,
  [88] = 52,
  [89] = 57,
  [90] = 52,
  [91] = 57,
  [92] = 52,
  [93] = 87,
  [94] = 94,
  [95] = 84,
  [96] = 96,
  [97] = 86,
  [98] = 98,
  [99] = 99,
  [100] = 100,
  [101] = 101,
  [102] = 102,
  [103] = 103,
  [104] = 104,
  [105] = 105,
  [106] = 106,
  [107] = 107,
  [108] = 108,
  [109] = 109,
  [110] = 110,
  [111] = 111,
  [112] = 112,
  [113] = 113,
  [114] = 114,
  [115] = 115,
};

static bool ts_lex(TSLexer *lexer, TSStateId state) {
  START_LEXER();
  eof = lexer->eof(lexer);
  switch (state) {
    case 0:
      if (eof) ADVANCE(39);
      ADVANCE_MAP(
        '"', 94,
        '&', 3,
        '\'', 91,
        '/', 6,
        '<', 40,
        '=', 48,
        '>', 41,
        'b', 15,
        'i', 19,
        's', 18,
        't', 11,
        'w', 32,
        '{', 99,
        '}', 100,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(37);
      END_STATE();
    case 1:
      if (lookahead == '"') ADVANCE(94);
      if (lookahead == '&') ADVANCE(3);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(96);
      END_STATE();
    case 2:
      if (lookahead == '"') ADVANCE(94);
      if (lookahead == '\'') ADVANCE(91);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(2);
      if (lookahead != 0 &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(50);
      END_STATE();
    case 3:
      if (lookahead == '#') ADVANCE(34);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(90);
      END_STATE();
    case 4:
      if (lookahead == '&') ADVANCE(3);
      if (lookahead == '\'') ADVANCE(91);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '{') ADVANCE(93);
      END_STATE();
    case 5:
      if (lookahead == '/') ADVANCE(6);
      if (lookahead == '=') ADVANCE(48);
      if (lookahead == '>') ADVANCE(41);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(5);
      if (('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 6:
      if (lookahead == '>') ADVANCE(46);
      END_STATE();
    case 7:
      if (lookahead == 'a') ADVANCE(30);
      END_STATE();
    case 8:
      if (lookahead == 'c') ADVANCE(14);
      END_STATE();
    case 9:
      if (lookahead == 'c') ADVANCE(16);
      END_STATE();
    case 10:
      if (lookahead == 'd') ADVANCE(12);
      END_STATE();
    case 11:
      if (lookahead == 'e') ADVANCE(20);
      END_STATE();
    case 12:
      if (lookahead == 'e') ADVANCE(102);
      END_STATE();
    case 13:
      if (lookahead == 'e') ADVANCE(42);
      END_STATE();
    case 14:
      if (lookahead == 'k') ADVANCE(44);
      END_STATE();
    case 15:
      if (lookahead == 'l') ADVANCE(23);
      END_STATE();
    case 16:
      if (lookahead == 'l') ADVANCE(31);
      END_STATE();
    case 17:
      if (lookahead == 'l') ADVANCE(7);
      END_STATE();
    case 18:
      if (lookahead == 'l') ADVANCE(21);
      END_STATE();
    case 19:
      if (lookahead == 'm') ADVANCE(25);
      if (lookahead == 'n') ADVANCE(9);
      END_STATE();
    case 20:
      if (lookahead == 'm') ADVANCE(24);
      END_STATE();
    case 21:
      if (lookahead == 'o') ADVANCE(28);
      END_STATE();
    case 22:
      if (lookahead == 'o') ADVANCE(26);
      END_STATE();
    case 23:
      if (lookahead == 'o') ADVANCE(8);
      END_STATE();
    case 24:
      if (lookahead == 'p') ADVANCE(17);
      END_STATE();
    case 25:
      if (lookahead == 'p') ADVANCE(22);
      END_STATE();
    case 26:
      if (lookahead == 'r') ADVANCE(29);
      END_STATE();
    case 27:
      if (lookahead == 's') ADVANCE(45);
      END_STATE();
    case 28:
      if (lookahead == 't') ADVANCE(43);
      END_STATE();
    case 29:
      if (lookahead == 't') ADVANCE(101);
      END_STATE();
    case 30:
      if (lookahead == 't') ADVANCE(13);
      END_STATE();
    case 31:
      if (lookahead == 'u') ADVANCE(10);
      END_STATE();
    case 32:
      if (lookahead == 'x') ADVANCE(27);
      END_STATE();
    case 33:
      if (lookahead == '{') ADVANCE(99);
      if (lookahead == '}') ADVANCE(100);
      if (lookahead != 0) ADVANCE(98);
      END_STATE();
    case 34:
      if (lookahead == 'X' ||
          lookahead == 'x') ADVANCE(36);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(56);
      END_STATE();
    case 35:
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 36:
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(61);
      END_STATE();
    case 37:
      if (eof) ADVANCE(39);
      ADVANCE_MAP(
        '"', 94,
        '&', 3,
        '\'', 91,
        '/', 6,
        '<', 40,
        '=', 48,
        '>', 41,
        'b', 15,
        'i', 19,
        's', 18,
        't', 11,
        'w', 32,
      );
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(37);
      END_STATE();
    case 38:
      if (eof) ADVANCE(39);
      if (lookahead == '&') ADVANCE(3);
      if (lookahead == '<') ADVANCE(40);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') SKIP(38);
      if (lookahead != 0 &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 39:
      ACCEPT_TOKEN(ts_builtin_sym_end);
      END_STATE();
    case 40:
      ACCEPT_TOKEN(anon_sym_LT);
      if (lookahead == '/') ADVANCE(47);
      END_STATE();
    case 41:
      ACCEPT_TOKEN(anon_sym_GT);
      END_STATE();
    case 42:
      ACCEPT_TOKEN(anon_sym_template);
      END_STATE();
    case 43:
      ACCEPT_TOKEN(anon_sym_slot);
      END_STATE();
    case 44:
      ACCEPT_TOKEN(anon_sym_block);
      END_STATE();
    case 45:
      ACCEPT_TOKEN(anon_sym_wxs);
      END_STATE();
    case 46:
      ACCEPT_TOKEN(anon_sym_SLASH_GT);
      END_STATE();
    case 47:
      ACCEPT_TOKEN(anon_sym_LT_SLASH);
      END_STATE();
    case 48:
      ACCEPT_TOKEN(anon_sym_EQ);
      END_STATE();
    case 49:
      ACCEPT_TOKEN(sym_attribute_name);
      if (lookahead == '-' ||
          lookahead == '.' ||
          ('0' <= lookahead && lookahead <= ':') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          lookahead == '_' ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(49);
      END_STATE();
    case 50:
      ACCEPT_TOKEN(sym_attribute_value);
      if (lookahead != 0 &&
          (lookahead < '\t' || '\r' < lookahead) &&
          lookahead != ' ' &&
          lookahead != '"' &&
          lookahead != '\'' &&
          (lookahead < '<' || '>' < lookahead)) ADVANCE(50);
      END_STATE();
    case 51:
      ACCEPT_TOKEN(sym_entity);
      END_STATE();
    case 52:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      END_STATE();
    case 53:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(52);
      END_STATE();
    case 54:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(53);
      END_STATE();
    case 55:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(54);
      END_STATE();
    case 56:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9')) ADVANCE(55);
      END_STATE();
    case 57:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(52);
      END_STATE();
    case 58:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(57);
      END_STATE();
    case 59:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(58);
      END_STATE();
    case 60:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(59);
      END_STATE();
    case 61:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'F') ||
          ('a' <= lookahead && lookahead <= 'f')) ADVANCE(60);
      END_STATE();
    case 62:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(52);
      END_STATE();
    case 63:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(62);
      END_STATE();
    case 64:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(63);
      END_STATE();
    case 65:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(64);
      END_STATE();
    case 66:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(65);
      END_STATE();
    case 67:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(66);
      END_STATE();
    case 68:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(67);
      END_STATE();
    case 69:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(68);
      END_STATE();
    case 70:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(69);
      END_STATE();
    case 71:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(70);
      END_STATE();
    case 72:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(71);
      END_STATE();
    case 73:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(72);
      END_STATE();
    case 74:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(73);
      END_STATE();
    case 75:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(74);
      END_STATE();
    case 76:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(75);
      END_STATE();
    case 77:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(76);
      END_STATE();
    case 78:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(77);
      END_STATE();
    case 79:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(78);
      END_STATE();
    case 80:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(79);
      END_STATE();
    case 81:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(80);
      END_STATE();
    case 82:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(81);
      END_STATE();
    case 83:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(82);
      END_STATE();
    case 84:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(83);
      END_STATE();
    case 85:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(84);
      END_STATE();
    case 86:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(85);
      END_STATE();
    case 87:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(86);
      END_STATE();
    case 88:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(87);
      END_STATE();
    case 89:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(88);
      END_STATE();
    case 90:
      ACCEPT_TOKEN(sym_entity);
      if (lookahead == ';') ADVANCE(51);
      if (('0' <= lookahead && lookahead <= '9') ||
          ('A' <= lookahead && lookahead <= 'Z') ||
          ('a' <= lookahead && lookahead <= 'z')) ADVANCE(89);
      END_STATE();
    case 91:
      ACCEPT_TOKEN(anon_sym_SQUOTE);
      END_STATE();
    case 92:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(92);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '\'' &&
          lookahead != '{') ADVANCE(93);
      END_STATE();
    case 93:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token1);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '\'' &&
          lookahead != '{') ADVANCE(93);
      END_STATE();
    case 94:
      ACCEPT_TOKEN(anon_sym_DQUOTE);
      END_STATE();
    case 95:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(95);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '&' &&
          lookahead != '{') ADVANCE(96);
      END_STATE();
    case 96:
      ACCEPT_TOKEN(aux_sym_quoted_attribute_value_token2);
      if (lookahead != 0 &&
          lookahead != '"' &&
          lookahead != '&' &&
          lookahead != '{') ADVANCE(96);
      END_STATE();
    case 97:
      ACCEPT_TOKEN(sym_text);
      if (('\t' <= lookahead && lookahead <= '\r') ||
          lookahead == ' ') ADVANCE(35);
      if (lookahead != 0 &&
          lookahead != '&' &&
          lookahead != '<' &&
          lookahead != '>' &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(97);
      END_STATE();
    case 98:
      ACCEPT_TOKEN(aux_sym__interpolation_text_token1);
      if (lookahead != 0 &&
          lookahead != '{' &&
          lookahead != '}') ADVANCE(98);
      END_STATE();
    case 99:
      ACCEPT_TOKEN(anon_sym_LBRACE);
      END_STATE();
    case 100:
      ACCEPT_TOKEN(anon_sym_RBRACE);
      END_STATE();
    case 101:
      ACCEPT_TOKEN(anon_sym_import);
      END_STATE();
    case 102:
      ACCEPT_TOKEN(anon_sym_include);
      END_STATE();
    default:
      return false;
  }
}

static const TSLexerMode ts_lex_modes[STATE_COUNT] = {
  [0] = {.lex_state = 0, .external_lex_state = 1},
  [1] = {.lex_state = 38, .external_lex_state = 2},
  [2] = {.lex_state = 38, .external_lex_state = 2},
  [3] = {.lex_state = 38, .external_lex_state = 2},
  [4] = {.lex_state = 38, .external_lex_state = 2},
  [5] = {.lex_state = 38, .external_lex_state = 2},
  [6] = {.lex_state = 38, .external_lex_state = 2},
  [7] = {.lex_state = 38, .external_lex_state = 2},
  [8] = {.lex_state = 38, .external_lex_state = 2},
  [9] = {.lex_state = 38, .external_lex_state = 2},
  [10] = {.lex_state = 38, .external_lex_state = 2},
  [11] = {.lex_state = 38, .external_lex_state = 2},
  [12] = {.lex_state = 33, .external_lex_state = 3},
  [13] = {.lex_state = 33, .external_lex_state = 3},
  [14] = {.lex_state = 0, .external_lex_state = 4},
  [15] = {.lex_state = 33, .external_lex_state = 3},
  [16] = {.lex_state = 33, .external_lex_state = 2},
  [17] = {.lex_state = 33, .external_lex_state = 3},
  [18] = {.lex_state = 33, .external_lex_state = 2},
  [19] = {.lex_state = 33, .external_lex_state = 3},
  [20] = {.lex_state = 33, .external_lex_state = 2},
  [21] = {.lex_state = 33, .external_lex_state = 3},
  [22] = {.lex_state = 33, .external_lex_state = 2},
  [23] = {.lex_state = 33, .external_lex_state = 2},
  [24] = {.lex_state = 33, .external_lex_state = 3},
  [25] = {.lex_state = 33, .external_lex_state = 3},
  [26] = {.lex_state = 33, .external_lex_state = 3},
  [27] = {.lex_state = 33, .external_lex_state = 3},
  [28] = {.lex_state = 33, .external_lex_state = 3},
  [29] = {.lex_state = 38, .external_lex_state = 2},
  [30] = {.lex_state = 38, .external_lex_state = 2},
  [31] = {.lex_state = 38, .external_lex_state = 2},
  [32] = {.lex_state = 38, .external_lex_state = 2},
  [33] = {.lex_state = 38, .external_lex_state = 2},
  [34] = {.lex_state = 38, .external_lex_state = 2},
  [35] = {.lex_state = 38, .external_lex_state = 2},
  [36] = {.lex_state = 38, .external_lex_state = 2},
  [37] = {.lex_state = 38, .external_lex_state = 2},
  [38] = {.lex_state = 38, .external_lex_state = 2},
  [39] = {.lex_state = 38, .external_lex_state = 2},
  [40] = {.lex_state = 38, .external_lex_state = 2},
  [41] = {.lex_state = 38, .external_lex_state = 2},
  [42] = {.lex_state = 38, .external_lex_state = 2},
  [43] = {.lex_state = 38, .external_lex_state = 2},
  [44] = {.lex_state = 38, .external_lex_state = 2},
  [45] = {.lex_state = 4, .external_lex_state = 2},
  [46] = {.lex_state = 1, .external_lex_state = 2},
  [47] = {.lex_state = 4, .external_lex_state = 2},
  [48] = {.lex_state = 1, .external_lex_state = 2},
  [49] = {.lex_state = 4, .external_lex_state = 2},
  [50] = {.lex_state = 1, .external_lex_state = 2},
  [51] = {.lex_state = 38, .external_lex_state = 2},
  [52] = {.lex_state = 38, .external_lex_state = 2},
  [53] = {.lex_state = 38, .external_lex_state = 2},
  [54] = {.lex_state = 38, .external_lex_state = 2},
  [55] = {.lex_state = 38, .external_lex_state = 2},
  [56] = {.lex_state = 38, .external_lex_state = 2},
  [57] = {.lex_state = 38, .external_lex_state = 2},
  [58] = {.lex_state = 38, .external_lex_state = 2},
  [59] = {.lex_state = 38, .external_lex_state = 2},
  [60] = {.lex_state = 5, .external_lex_state = 5},
  [61] = {.lex_state = 38, .external_lex_state = 2},
  [62] = {.lex_state = 5, .external_lex_state = 5},
  [63] = {.lex_state = 5, .external_lex_state = 5},
  [64] = {.lex_state = 38, .external_lex_state = 2},
  [65] = {.lex_state = 38, .external_lex_state = 2},
  [66] = {.lex_state = 38, .external_lex_state = 2},
  [67] = {.lex_state = 5, .external_lex_state = 5},
  [68] = {.lex_state = 5, .external_lex_state = 5},
  [69] = {.lex_state = 5, .external_lex_state = 5},
  [70] = {.lex_state = 5, .external_lex_state = 5},
  [71] = {.lex_state = 38, .external_lex_state = 2},
  [72] = {.lex_state = 5, .external_lex_state = 5},
  [73] = {.lex_state = 5, .external_lex_state = 5},
  [74] = {.lex_state = 38, .external_lex_state = 2},
  [75] = {.lex_state = 5, .external_lex_state = 5},
  [76] = {.lex_state = 5, .external_lex_state = 5},
  [77] = {.lex_state = 38, .external_lex_state = 2},
  [78] = {.lex_state = 1, .external_lex_state = 2},
  [79] = {.lex_state = 5, .external_lex_state = 5},
  [80] = {.lex_state = 5, .external_lex_state = 5},
  [81] = {.lex_state = 5, .external_lex_state = 5},
  [82] = {.lex_state = 5, .external_lex_state = 5},
  [83] = {.lex_state = 33, .external_lex_state = 3},
  [84] = {.lex_state = 33, .external_lex_state = 2},
  [85] = {.lex_state = 33, .external_lex_state = 3},
  [86] = {.lex_state = 33, .external_lex_state = 3},
  [87] = {.lex_state = 33, .external_lex_state = 2},
  [88] = {.lex_state = 33, .external_lex_state = 2},
  [89] = {.lex_state = 33, .external_lex_state = 2},
  [90] = {.lex_state = 4, .external_lex_state = 2},
  [91] = {.lex_state = 4, .external_lex_state = 2},
  [92] = {.lex_state = 1, .external_lex_state = 2},
  [93] = {.lex_state = 33, .external_lex_state = 3},
  [94] = {.lex_state = 2, .external_lex_state = 6},
  [95] = {.lex_state = 33, .external_lex_state = 3},
  [96] = {.lex_state = 5, .external_lex_state = 5},
  [97] = {.lex_state = 33, .external_lex_state = 2},
  [98] = {.lex_state = 5, .external_lex_state = 5},
  [99] = {.lex_state = 5, .external_lex_state = 5},
  [100] = {.lex_state = 0, .external_lex_state = 7},
  [101] = {.lex_state = 5, .external_lex_state = 5},
  [102] = {.lex_state = 0, .external_lex_state = 8},
  [103] = {.lex_state = 0, .external_lex_state = 6},
  [104] = {.lex_state = 0, .external_lex_state = 7},
  [105] = {.lex_state = 0, .external_lex_state = 7},
  [106] = {.lex_state = 0, .external_lex_state = 6},
  [107] = {.lex_state = 0, .external_lex_state = 6},
  [108] = {.lex_state = 0, .external_lex_state = 6},
  [109] = {.lex_state = 0, .external_lex_state = 6},
  [110] = {.lex_state = 0, .external_lex_state = 6},
  [111] = {.lex_state = 0, .external_lex_state = 6},
  [112] = {.lex_state = 0, .external_lex_state = 6},
  [113] = {.lex_state = 0, .external_lex_state = 6},
  [114] = {.lex_state = 0, .external_lex_state = 6},
  [115] = {.lex_state = 0, .external_lex_state = 6},
};

static const uint16_t ts_parse_table[LARGE_STATE_COUNT][SYMBOL_COUNT] = {
  [STATE(0)] = {
    [ts_builtin_sym_end] = ACTIONS(1),
    [anon_sym_LT] = ACTIONS(1),
    [anon_sym_GT] = ACTIONS(1),
    [anon_sym_template] = ACTIONS(1),
    [anon_sym_slot] = ACTIONS(1),
    [anon_sym_block] = ACTIONS(1),
    [anon_sym_wxs] = ACTIONS(1),
    [anon_sym_SLASH_GT] = ACTIONS(1),
    [anon_sym_LT_SLASH] = ACTIONS(1),
    [anon_sym_EQ] = ACTIONS(1),
    [sym_entity] = ACTIONS(1),
    [anon_sym_SQUOTE] = ACTIONS(1),
    [anon_sym_DQUOTE] = ACTIONS(1),
    [anon_sym_LBRACE] = ACTIONS(1),
    [anon_sym_RBRACE] = ACTIONS(1),
    [anon_sym_import] = ACTIONS(1),
    [anon_sym_include] = ACTIONS(1),
    [sym__start_tag_name] = ACTIONS(1),
    [sym__end_tag_name] = ACTIONS(1),
    [sym_raw_text] = ACTIONS(1),
    [sym_comment] = ACTIONS(3),
    [sym__interpolation_start] = ACTIONS(1),
    [sym__interpolation_end] = ACTIONS(1),
  },
  [STATE(1)] = {
    [sym_document] = STATE(112),
    [sym__node] = STATE(11),
    [sym_element] = STATE(11),
    [sym_start_tag] = STATE(2),
    [sym_self_closing_tag] = STATE(29),
    [sym_interpolation] = STATE(11),
    [sym_import_statement] = STATE(11),
    [sym_include_statement] = STATE(11),
    [sym_template_element] = STATE(11),
    [sym_template_start_tag] = STATE(3),
    [sym_slot_element] = STATE(11),
    [sym_slot_start_tag] = STATE(4),
    [sym_block_element] = STATE(11),
    [sym_wxs_element] = STATE(11),
    [sym_block_start_tag] = STATE(5),
    [sym_wxs_start_tag] = STATE(100),
    [aux_sym_document_repeat1] = STATE(11),
    [ts_builtin_sym_end] = ACTIONS(5),
    [anon_sym_LT] = ACTIONS(7),
    [sym_entity] = ACTIONS(9),
    [sym_text] = ACTIONS(9),
    [sym_comment] = ACTIONS(3),
    [sym__interpolation_start] = ACTIONS(11),
  },
};

static const uint16_t ts_small_parse_table[] = {
  [0] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_template_start_tag,
    STATE(4), 1,
      sym_slot_start_tag,
    STATE(5), 1,
      sym_block_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(54), 1,
      sym_end_tag,
    STATE(100), 1,
      sym_wxs_start_tag,
    ACTIONS(17), 2,
      sym_entity,
      sym_text,
    STATE(6), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [50] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_template_start_tag,
    STATE(4), 1,
      sym_slot_start_tag,
    STATE(5), 1,
      sym_block_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(56), 1,
      sym_template_end_tag,
    STATE(100), 1,
      sym_wxs_start_tag,
    ACTIONS(21), 2,
      sym_entity,
      sym_text,
    STATE(8), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [100] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(23), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_template_start_tag,
    STATE(4), 1,
      sym_slot_start_tag,
    STATE(5), 1,
      sym_block_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(51), 1,
      sym_slot_end_tag,
    STATE(100), 1,
      sym_wxs_start_tag,
    ACTIONS(25), 2,
      sym_entity,
      sym_text,
    STATE(7), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [150] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_template_start_tag,
    STATE(4), 1,
      sym_slot_start_tag,
    STATE(5), 1,
      sym_block_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(53), 1,
      sym_block_end_tag,
    STATE(100), 1,
      sym_wxs_start_tag,
    ACTIONS(29), 2,
      sym_entity,
      sym_text,
    STATE(9), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [200] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(15), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_template_start_tag,
    STATE(4), 1,
      sym_slot_start_tag,
    STATE(5), 1,
      sym_block_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(33), 1,
      sym_end_tag,
    STATE(100), 1,
      sym_wxs_start_tag,
    ACTIONS(31), 2,
      sym_entity,
      sym_text,
    STATE(10), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [250] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(23), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_template_start_tag,
    STATE(4), 1,
      sym_slot_start_tag,
    STATE(5), 1,
      sym_block_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(35), 1,
      sym_slot_end_tag,
    STATE(100), 1,
      sym_wxs_start_tag,
    ACTIONS(31), 2,
      sym_entity,
      sym_text,
    STATE(10), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [300] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(19), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_template_start_tag,
    STATE(4), 1,
      sym_slot_start_tag,
    STATE(5), 1,
      sym_block_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(34), 1,
      sym_template_end_tag,
    STATE(100), 1,
      sym_wxs_start_tag,
    ACTIONS(31), 2,
      sym_entity,
      sym_text,
    STATE(10), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [350] = 13,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(13), 1,
      anon_sym_LT,
    ACTIONS(27), 1,
      anon_sym_LT_SLASH,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_template_start_tag,
    STATE(4), 1,
      sym_slot_start_tag,
    STATE(5), 1,
      sym_block_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(36), 1,
      sym_block_end_tag,
    STATE(100), 1,
      sym_wxs_start_tag,
    ACTIONS(31), 2,
      sym_entity,
      sym_text,
    STATE(10), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [400] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(35), 1,
      anon_sym_LT,
    ACTIONS(41), 1,
      sym__interpolation_start,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_template_start_tag,
    STATE(4), 1,
      sym_slot_start_tag,
    STATE(5), 1,
      sym_block_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(100), 1,
      sym_wxs_start_tag,
    ACTIONS(33), 2,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
    ACTIONS(38), 2,
      sym_entity,
      sym_text,
    STATE(10), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [448] = 12,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(7), 1,
      anon_sym_LT,
    ACTIONS(11), 1,
      sym__interpolation_start,
    ACTIONS(44), 1,
      ts_builtin_sym_end,
    STATE(2), 1,
      sym_start_tag,
    STATE(3), 1,
      sym_template_start_tag,
    STATE(4), 1,
      sym_slot_start_tag,
    STATE(5), 1,
      sym_block_start_tag,
    STATE(29), 1,
      sym_self_closing_tag,
    STATE(100), 1,
      sym_wxs_start_tag,
    ACTIONS(31), 2,
      sym_entity,
      sym_text,
    STATE(10), 10,
      sym__node,
      sym_element,
      sym_interpolation,
      sym_import_statement,
      sym_include_statement,
      sym_template_element,
      sym_slot_element,
      sym_block_element,
      sym_wxs_element,
      aux_sym_document_repeat1,
  [495] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      sym__interpolation_start,
    ACTIONS(52), 1,
      sym__interpolation_end,
    STATE(19), 1,
      aux_sym__interpolation_text,
    STATE(86), 2,
      sym_interpolation,
      sym__js_brace_expression,
  [518] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      sym__interpolation_start,
    ACTIONS(54), 1,
      sym__interpolation_end,
    STATE(19), 1,
      aux_sym__interpolation_text,
    STATE(86), 2,
      sym_interpolation,
      sym__js_brace_expression,
  [541] = 8,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(56), 1,
      anon_sym_template,
    ACTIONS(58), 1,
      anon_sym_slot,
    ACTIONS(60), 1,
      anon_sym_block,
    ACTIONS(62), 1,
      anon_sym_wxs,
    ACTIONS(64), 1,
      anon_sym_import,
    ACTIONS(66), 1,
      anon_sym_include,
    ACTIONS(68), 1,
      sym__start_tag_name,
  [566] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      sym__interpolation_start,
    ACTIONS(70), 1,
      sym__interpolation_end,
    STATE(17), 1,
      aux_sym__interpolation_text,
    STATE(86), 2,
      sym_interpolation,
      sym__js_brace_expression,
  [589] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(74), 1,
      anon_sym_LBRACE,
    ACTIONS(76), 1,
      anon_sym_RBRACE,
    ACTIONS(78), 1,
      sym__interpolation_start,
    STATE(18), 1,
      aux_sym__interpolation_text,
    STATE(97), 2,
      sym_interpolation,
      sym__js_brace_expression,
  [612] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      sym__interpolation_start,
    ACTIONS(80), 1,
      sym__interpolation_end,
    STATE(19), 1,
      aux_sym__interpolation_text,
    STATE(86), 2,
      sym_interpolation,
      sym__js_brace_expression,
  [635] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(74), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      sym__interpolation_start,
    ACTIONS(82), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      aux_sym__interpolation_text,
    STATE(97), 2,
      sym_interpolation,
      sym__js_brace_expression,
  [658] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(84), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(87), 1,
      anon_sym_LBRACE,
    ACTIONS(90), 1,
      sym__interpolation_start,
    ACTIONS(93), 1,
      sym__interpolation_end,
    STATE(19), 1,
      aux_sym__interpolation_text,
    STATE(86), 2,
      sym_interpolation,
      sym__js_brace_expression,
  [681] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(93), 1,
      anon_sym_RBRACE,
    ACTIONS(95), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(98), 1,
      anon_sym_LBRACE,
    ACTIONS(101), 1,
      sym__interpolation_start,
    STATE(20), 1,
      aux_sym__interpolation_text,
    STATE(97), 2,
      sym_interpolation,
      sym__js_brace_expression,
  [704] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      sym__interpolation_start,
    ACTIONS(104), 1,
      sym__interpolation_end,
    STATE(12), 1,
      aux_sym__interpolation_text,
    STATE(86), 2,
      sym_interpolation,
      sym__js_brace_expression,
  [727] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(74), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      sym__interpolation_start,
    ACTIONS(106), 1,
      anon_sym_RBRACE,
    STATE(23), 1,
      aux_sym__interpolation_text,
    STATE(97), 2,
      sym_interpolation,
      sym__js_brace_expression,
  [750] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(72), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(74), 1,
      anon_sym_LBRACE,
    ACTIONS(78), 1,
      sym__interpolation_start,
    ACTIONS(108), 1,
      anon_sym_RBRACE,
    STATE(20), 1,
      aux_sym__interpolation_text,
    STATE(97), 2,
      sym_interpolation,
      sym__js_brace_expression,
  [773] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      sym__interpolation_start,
    ACTIONS(110), 1,
      sym__interpolation_end,
    STATE(25), 1,
      aux_sym__interpolation_text,
    STATE(86), 2,
      sym_interpolation,
      sym__js_brace_expression,
  [796] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      sym__interpolation_start,
    ACTIONS(112), 1,
      sym__interpolation_end,
    STATE(19), 1,
      aux_sym__interpolation_text,
    STATE(86), 2,
      sym_interpolation,
      sym__js_brace_expression,
  [819] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      sym__interpolation_start,
    ACTIONS(114), 1,
      sym__interpolation_end,
    STATE(27), 1,
      aux_sym__interpolation_text,
    STATE(86), 2,
      sym_interpolation,
      sym__js_brace_expression,
  [842] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      sym__interpolation_start,
    ACTIONS(116), 1,
      sym__interpolation_end,
    STATE(19), 1,
      aux_sym__interpolation_text,
    STATE(86), 2,
      sym_interpolation,
      sym__js_brace_expression,
  [865] = 7,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(46), 1,
      aux_sym__interpolation_text_token1,
    ACTIONS(48), 1,
      anon_sym_LBRACE,
    ACTIONS(50), 1,
      sym__interpolation_start,
    ACTIONS(118), 1,
      sym__interpolation_end,
    STATE(13), 1,
      aux_sym__interpolation_text,
    STATE(86), 2,
      sym_interpolation,
      sym__js_brace_expression,
  [888] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(122), 1,
      anon_sym_LT,
    ACTIONS(120), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [902] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(126), 1,
      anon_sym_LT,
    ACTIONS(124), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [916] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(130), 1,
      anon_sym_LT,
    ACTIONS(128), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [930] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(134), 1,
      anon_sym_LT,
    ACTIONS(132), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [944] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(138), 1,
      anon_sym_LT,
    ACTIONS(136), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [958] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(142), 1,
      anon_sym_LT,
    ACTIONS(140), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [972] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(146), 1,
      anon_sym_LT,
    ACTIONS(144), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [986] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(150), 1,
      anon_sym_LT,
    ACTIONS(148), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1000] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(154), 1,
      anon_sym_LT,
    ACTIONS(152), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1014] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(158), 1,
      anon_sym_LT,
    ACTIONS(156), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1028] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(162), 1,
      anon_sym_LT,
    ACTIONS(160), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1042] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(166), 1,
      anon_sym_LT,
    ACTIONS(164), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1056] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(170), 1,
      anon_sym_LT,
    ACTIONS(168), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1070] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(174), 1,
      anon_sym_LT,
    ACTIONS(172), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1084] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(178), 1,
      anon_sym_LT,
    ACTIONS(176), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1098] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(182), 1,
      anon_sym_LT,
    ACTIONS(180), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1112] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(184), 1,
      sym_entity,
    ACTIONS(186), 1,
      anon_sym_SQUOTE,
    ACTIONS(188), 1,
      aux_sym_quoted_attribute_value_token1,
    ACTIONS(190), 1,
      sym__interpolation_start,
    STATE(47), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat1,
  [1132] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(186), 1,
      anon_sym_DQUOTE,
    ACTIONS(192), 1,
      sym_entity,
    ACTIONS(194), 1,
      aux_sym_quoted_attribute_value_token2,
    ACTIONS(196), 1,
      sym__interpolation_start,
    STATE(48), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat2,
  [1152] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(190), 1,
      sym__interpolation_start,
    ACTIONS(198), 1,
      sym_entity,
    ACTIONS(200), 1,
      anon_sym_SQUOTE,
    ACTIONS(202), 1,
      aux_sym_quoted_attribute_value_token1,
    STATE(49), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat1,
  [1172] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(196), 1,
      sym__interpolation_start,
    ACTIONS(200), 1,
      anon_sym_DQUOTE,
    ACTIONS(204), 1,
      sym_entity,
    ACTIONS(206), 1,
      aux_sym_quoted_attribute_value_token2,
    STATE(50), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat2,
  [1192] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(208), 1,
      sym_entity,
    ACTIONS(211), 1,
      anon_sym_SQUOTE,
    ACTIONS(213), 1,
      aux_sym_quoted_attribute_value_token1,
    ACTIONS(216), 1,
      sym__interpolation_start,
    STATE(49), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat1,
  [1212] = 6,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(219), 1,
      sym_entity,
    ACTIONS(222), 1,
      anon_sym_DQUOTE,
    ACTIONS(224), 1,
      aux_sym_quoted_attribute_value_token2,
    ACTIONS(227), 1,
      sym__interpolation_start,
    STATE(50), 2,
      sym_interpolation,
      aux_sym_quoted_attribute_value_repeat2,
  [1232] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(232), 1,
      anon_sym_LT,
    ACTIONS(230), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1246] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(236), 1,
      anon_sym_LT,
    ACTIONS(234), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1260] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(240), 1,
      anon_sym_LT,
    ACTIONS(238), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1274] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(244), 1,
      anon_sym_LT,
    ACTIONS(242), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1288] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(248), 1,
      anon_sym_LT,
    ACTIONS(246), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1302] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(252), 1,
      anon_sym_LT,
    ACTIONS(250), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1316] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(256), 1,
      anon_sym_LT,
    ACTIONS(254), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1330] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(260), 1,
      anon_sym_LT,
    ACTIONS(258), 5,
      sym__interpolation_start,
      ts_builtin_sym_end,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1344] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(262), 1,
      anon_sym_LT,
    ACTIONS(264), 4,
      sym__interpolation_start,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1357] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(266), 1,
      anon_sym_GT,
    ACTIONS(268), 1,
      anon_sym_SLASH_GT,
    ACTIONS(270), 1,
      sym_attribute_name,
    STATE(63), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1374] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(272), 1,
      anon_sym_LT,
    ACTIONS(274), 4,
      sym__interpolation_start,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1387] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_SLASH_GT,
    ACTIONS(270), 1,
      sym_attribute_name,
    ACTIONS(276), 1,
      anon_sym_GT,
    STATE(63), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1404] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(280), 1,
      sym_attribute_name,
    ACTIONS(278), 2,
      anon_sym_GT,
      anon_sym_SLASH_GT,
    STATE(63), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1419] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(283), 1,
      anon_sym_LT,
    ACTIONS(285), 4,
      sym__interpolation_start,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1432] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(287), 1,
      anon_sym_LT,
    ACTIONS(289), 4,
      sym__interpolation_start,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1445] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(291), 1,
      anon_sym_LT,
    ACTIONS(293), 4,
      sym__interpolation_start,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1458] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_attribute_name,
    ACTIONS(295), 1,
      anon_sym_GT,
    ACTIONS(297), 1,
      anon_sym_SLASH_GT,
    STATE(68), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1475] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_SLASH_GT,
    ACTIONS(270), 1,
      sym_attribute_name,
    ACTIONS(299), 1,
      anon_sym_GT,
    STATE(63), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1492] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_attribute_name,
    ACTIONS(297), 1,
      anon_sym_SLASH_GT,
    ACTIONS(301), 1,
      anon_sym_GT,
    STATE(75), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1509] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_attribute_name,
    ACTIONS(297), 1,
      anon_sym_SLASH_GT,
    ACTIONS(303), 1,
      anon_sym_GT,
    STATE(72), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1526] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(305), 1,
      anon_sym_LT,
    ACTIONS(307), 4,
      sym__interpolation_start,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1539] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_SLASH_GT,
    ACTIONS(270), 1,
      sym_attribute_name,
    ACTIONS(309), 1,
      anon_sym_GT,
    STATE(63), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1556] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_attribute_name,
    ACTIONS(297), 1,
      anon_sym_SLASH_GT,
    ACTIONS(311), 1,
      anon_sym_GT,
    STATE(60), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1573] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(313), 1,
      anon_sym_LT,
    ACTIONS(315), 4,
      sym__interpolation_start,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1586] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(268), 1,
      anon_sym_SLASH_GT,
    ACTIONS(270), 1,
      sym_attribute_name,
    ACTIONS(317), 1,
      anon_sym_GT,
    STATE(63), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1603] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_attribute_name,
    ACTIONS(297), 1,
      anon_sym_SLASH_GT,
    ACTIONS(319), 1,
      anon_sym_GT,
    STATE(62), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1620] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(321), 1,
      anon_sym_LT,
    ACTIONS(323), 4,
      sym__interpolation_start,
      anon_sym_LT_SLASH,
      sym_entity,
      sym_text,
  [1633] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 2,
      sym__interpolation_start,
      aux_sym_quoted_attribute_value_token2,
    ACTIONS(256), 2,
      sym_entity,
      anon_sym_DQUOTE,
  [1645] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_attribute_name,
    ACTIONS(325), 1,
      anon_sym_SLASH_GT,
    STATE(63), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1659] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_attribute_name,
    ACTIONS(327), 1,
      anon_sym_SLASH_GT,
    STATE(81), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1673] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_attribute_name,
    ACTIONS(329), 1,
      anon_sym_SLASH_GT,
    STATE(63), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1687] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(333), 1,
      anon_sym_EQ,
    ACTIONS(331), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1699] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 4,
      sym__interpolation_start,
      sym__interpolation_end,
      aux_sym__interpolation_text_token1,
      anon_sym_LBRACE,
  [1709] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 4,
      sym__interpolation_start,
      aux_sym__interpolation_text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1719] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 4,
      sym__interpolation_start,
      sym__interpolation_end,
      aux_sym__interpolation_text_token1,
      anon_sym_LBRACE,
  [1729] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 4,
      sym__interpolation_start,
      sym__interpolation_end,
      aux_sym__interpolation_text_token1,
      anon_sym_LBRACE,
  [1739] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 4,
      sym__interpolation_start,
      aux_sym__interpolation_text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1749] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 4,
      sym__interpolation_start,
      aux_sym__interpolation_text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1759] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 4,
      sym__interpolation_start,
      aux_sym__interpolation_text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1769] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 2,
      sym__interpolation_start,
      aux_sym_quoted_attribute_value_token1,
    ACTIONS(236), 2,
      sym_entity,
      anon_sym_SQUOTE,
  [1781] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(254), 2,
      sym__interpolation_start,
      aux_sym_quoted_attribute_value_token1,
    ACTIONS(256), 2,
      sym_entity,
      anon_sym_SQUOTE,
  [1793] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(234), 2,
      sym__interpolation_start,
      aux_sym_quoted_attribute_value_token2,
    ACTIONS(236), 2,
      sym_entity,
      anon_sym_DQUOTE,
  [1805] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(339), 4,
      sym__interpolation_start,
      sym__interpolation_end,
      aux_sym__interpolation_text_token1,
      anon_sym_LBRACE,
  [1815] = 5,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(341), 1,
      sym_attribute_value,
    ACTIONS(343), 1,
      anon_sym_SQUOTE,
    ACTIONS(345), 1,
      anon_sym_DQUOTE,
    STATE(101), 1,
      sym_quoted_attribute_value,
  [1831] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(335), 4,
      sym__interpolation_start,
      sym__interpolation_end,
      aux_sym__interpolation_text_token1,
      anon_sym_LBRACE,
  [1841] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(270), 1,
      sym_attribute_name,
    ACTIONS(347), 1,
      anon_sym_SLASH_GT,
    STATE(79), 2,
      sym_attribute,
      aux_sym_start_tag_repeat1,
  [1855] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(337), 4,
      sym__interpolation_start,
      aux_sym__interpolation_text_token1,
      anon_sym_LBRACE,
      anon_sym_RBRACE,
  [1865] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(349), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1874] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(351), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1883] = 4,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_LT_SLASH,
    ACTIONS(355), 1,
      sym_raw_text,
    STATE(55), 1,
      sym_wxs_end_tag,
  [1896] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(357), 3,
      anon_sym_GT,
      anon_sym_SLASH_GT,
      sym_attribute_name,
  [1905] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(359), 2,
      sym__end_tag_name,
      anon_sym_wxs,
  [1913] = 3,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(353), 1,
      anon_sym_LT_SLASH,
    STATE(37), 1,
      sym_wxs_end_tag,
  [1923] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(361), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1931] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(363), 2,
      sym_raw_text,
      anon_sym_LT_SLASH,
  [1939] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(365), 1,
      anon_sym_block,
  [1946] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(367), 1,
      anon_sym_GT,
  [1953] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(369), 1,
      anon_sym_GT,
  [1960] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(371), 1,
      anon_sym_GT,
  [1967] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(373), 1,
      anon_sym_GT,
  [1974] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(375), 1,
      anon_sym_template,
  [1981] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(377), 1,
      ts_builtin_sym_end,
  [1988] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(379), 1,
      anon_sym_wxs,
  [1995] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(381), 1,
      anon_sym_slot,
  [2002] = 2,
    ACTIONS(3), 1,
      sym_comment,
    ACTIONS(383), 1,
      anon_sym_GT,
};

static const uint32_t ts_small_parse_table_map[] = {
  [SMALL_STATE(2)] = 0,
  [SMALL_STATE(3)] = 50,
  [SMALL_STATE(4)] = 100,
  [SMALL_STATE(5)] = 150,
  [SMALL_STATE(6)] = 200,
  [SMALL_STATE(7)] = 250,
  [SMALL_STATE(8)] = 300,
  [SMALL_STATE(9)] = 350,
  [SMALL_STATE(10)] = 400,
  [SMALL_STATE(11)] = 448,
  [SMALL_STATE(12)] = 495,
  [SMALL_STATE(13)] = 518,
  [SMALL_STATE(14)] = 541,
  [SMALL_STATE(15)] = 566,
  [SMALL_STATE(16)] = 589,
  [SMALL_STATE(17)] = 612,
  [SMALL_STATE(18)] = 635,
  [SMALL_STATE(19)] = 658,
  [SMALL_STATE(20)] = 681,
  [SMALL_STATE(21)] = 704,
  [SMALL_STATE(22)] = 727,
  [SMALL_STATE(23)] = 750,
  [SMALL_STATE(24)] = 773,
  [SMALL_STATE(25)] = 796,
  [SMALL_STATE(26)] = 819,
  [SMALL_STATE(27)] = 842,
  [SMALL_STATE(28)] = 865,
  [SMALL_STATE(29)] = 888,
  [SMALL_STATE(30)] = 902,
  [SMALL_STATE(31)] = 916,
  [SMALL_STATE(32)] = 930,
  [SMALL_STATE(33)] = 944,
  [SMALL_STATE(34)] = 958,
  [SMALL_STATE(35)] = 972,
  [SMALL_STATE(36)] = 986,
  [SMALL_STATE(37)] = 1000,
  [SMALL_STATE(38)] = 1014,
  [SMALL_STATE(39)] = 1028,
  [SMALL_STATE(40)] = 1042,
  [SMALL_STATE(41)] = 1056,
  [SMALL_STATE(42)] = 1070,
  [SMALL_STATE(43)] = 1084,
  [SMALL_STATE(44)] = 1098,
  [SMALL_STATE(45)] = 1112,
  [SMALL_STATE(46)] = 1132,
  [SMALL_STATE(47)] = 1152,
  [SMALL_STATE(48)] = 1172,
  [SMALL_STATE(49)] = 1192,
  [SMALL_STATE(50)] = 1212,
  [SMALL_STATE(51)] = 1232,
  [SMALL_STATE(52)] = 1246,
  [SMALL_STATE(53)] = 1260,
  [SMALL_STATE(54)] = 1274,
  [SMALL_STATE(55)] = 1288,
  [SMALL_STATE(56)] = 1302,
  [SMALL_STATE(57)] = 1316,
  [SMALL_STATE(58)] = 1330,
  [SMALL_STATE(59)] = 1344,
  [SMALL_STATE(60)] = 1357,
  [SMALL_STATE(61)] = 1374,
  [SMALL_STATE(62)] = 1387,
  [SMALL_STATE(63)] = 1404,
  [SMALL_STATE(64)] = 1419,
  [SMALL_STATE(65)] = 1432,
  [SMALL_STATE(66)] = 1445,
  [SMALL_STATE(67)] = 1458,
  [SMALL_STATE(68)] = 1475,
  [SMALL_STATE(69)] = 1492,
  [SMALL_STATE(70)] = 1509,
  [SMALL_STATE(71)] = 1526,
  [SMALL_STATE(72)] = 1539,
  [SMALL_STATE(73)] = 1556,
  [SMALL_STATE(74)] = 1573,
  [SMALL_STATE(75)] = 1586,
  [SMALL_STATE(76)] = 1603,
  [SMALL_STATE(77)] = 1620,
  [SMALL_STATE(78)] = 1633,
  [SMALL_STATE(79)] = 1645,
  [SMALL_STATE(80)] = 1659,
  [SMALL_STATE(81)] = 1673,
  [SMALL_STATE(82)] = 1687,
  [SMALL_STATE(83)] = 1699,
  [SMALL_STATE(84)] = 1709,
  [SMALL_STATE(85)] = 1719,
  [SMALL_STATE(86)] = 1729,
  [SMALL_STATE(87)] = 1739,
  [SMALL_STATE(88)] = 1749,
  [SMALL_STATE(89)] = 1759,
  [SMALL_STATE(90)] = 1769,
  [SMALL_STATE(91)] = 1781,
  [SMALL_STATE(92)] = 1793,
  [SMALL_STATE(93)] = 1805,
  [SMALL_STATE(94)] = 1815,
  [SMALL_STATE(95)] = 1831,
  [SMALL_STATE(96)] = 1841,
  [SMALL_STATE(97)] = 1855,
  [SMALL_STATE(98)] = 1865,
  [SMALL_STATE(99)] = 1874,
  [SMALL_STATE(100)] = 1883,
  [SMALL_STATE(101)] = 1896,
  [SMALL_STATE(102)] = 1905,
  [SMALL_STATE(103)] = 1913,
  [SMALL_STATE(104)] = 1923,
  [SMALL_STATE(105)] = 1931,
  [SMALL_STATE(106)] = 1939,
  [SMALL_STATE(107)] = 1946,
  [SMALL_STATE(108)] = 1953,
  [SMALL_STATE(109)] = 1960,
  [SMALL_STATE(110)] = 1967,
  [SMALL_STATE(111)] = 1974,
  [SMALL_STATE(112)] = 1981,
  [SMALL_STATE(113)] = 1988,
  [SMALL_STATE(114)] = 1995,
  [SMALL_STATE(115)] = 2002,
};

static const TSParseActionEntry ts_parse_actions[] = {
  [0] = {.entry = {.count = 0, .reusable = false}},
  [1] = {.entry = {.count = 1, .reusable = false}}, RECOVER(),
  [3] = {.entry = {.count = 1, .reusable = true}}, SHIFT_EXTRA(),
  [5] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 0, 0, 0),
  [7] = {.entry = {.count = 1, .reusable = true}}, SHIFT(14),
  [9] = {.entry = {.count = 1, .reusable = true}}, SHIFT(11),
  [11] = {.entry = {.count = 1, .reusable = true}}, SHIFT(15),
  [13] = {.entry = {.count = 1, .reusable = false}}, SHIFT(14),
  [15] = {.entry = {.count = 1, .reusable = true}}, SHIFT(102),
  [17] = {.entry = {.count = 1, .reusable = true}}, SHIFT(6),
  [19] = {.entry = {.count = 1, .reusable = true}}, SHIFT(111),
  [21] = {.entry = {.count = 1, .reusable = true}}, SHIFT(8),
  [23] = {.entry = {.count = 1, .reusable = true}}, SHIFT(114),
  [25] = {.entry = {.count = 1, .reusable = true}}, SHIFT(7),
  [27] = {.entry = {.count = 1, .reusable = true}}, SHIFT(106),
  [29] = {.entry = {.count = 1, .reusable = true}}, SHIFT(9),
  [31] = {.entry = {.count = 1, .reusable = true}}, SHIFT(10),
  [33] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0),
  [35] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(14),
  [38] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(10),
  [41] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_document_repeat1, 2, 0, 0), SHIFT_REPEAT(15),
  [44] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_document, 1, 0, 0),
  [46] = {.entry = {.count = 1, .reusable = true}}, SHIFT(86),
  [48] = {.entry = {.count = 1, .reusable = true}}, SHIFT(16),
  [50] = {.entry = {.count = 1, .reusable = true}}, SHIFT(21),
  [52] = {.entry = {.count = 1, .reusable = true}}, SHIFT(85),
  [54] = {.entry = {.count = 1, .reusable = true}}, SHIFT(78),
  [56] = {.entry = {.count = 1, .reusable = true}}, SHIFT(70),
  [58] = {.entry = {.count = 1, .reusable = true}}, SHIFT(69),
  [60] = {.entry = {.count = 1, .reusable = true}}, SHIFT(73),
  [62] = {.entry = {.count = 1, .reusable = true}}, SHIFT(76),
  [64] = {.entry = {.count = 1, .reusable = true}}, SHIFT(96),
  [66] = {.entry = {.count = 1, .reusable = true}}, SHIFT(80),
  [68] = {.entry = {.count = 1, .reusable = true}}, SHIFT(67),
  [70] = {.entry = {.count = 1, .reusable = true}}, SHIFT(52),
  [72] = {.entry = {.count = 1, .reusable = true}}, SHIFT(97),
  [74] = {.entry = {.count = 1, .reusable = true}}, SHIFT(22),
  [76] = {.entry = {.count = 1, .reusable = true}}, SHIFT(95),
  [78] = {.entry = {.count = 1, .reusable = true}}, SHIFT(24),
  [80] = {.entry = {.count = 1, .reusable = true}}, SHIFT(57),
  [82] = {.entry = {.count = 1, .reusable = true}}, SHIFT(93),
  [84] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__interpolation_text, 2, 0, 0), SHIFT_REPEAT(86),
  [87] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__interpolation_text, 2, 0, 0), SHIFT_REPEAT(16),
  [90] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__interpolation_text, 2, 0, 0), SHIFT_REPEAT(21),
  [93] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__interpolation_text, 2, 0, 0),
  [95] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__interpolation_text, 2, 0, 0), SHIFT_REPEAT(97),
  [98] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__interpolation_text, 2, 0, 0), SHIFT_REPEAT(22),
  [101] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym__interpolation_text, 2, 0, 0), SHIFT_REPEAT(24),
  [104] = {.entry = {.count = 1, .reusable = true}}, SHIFT(83),
  [106] = {.entry = {.count = 1, .reusable = true}}, SHIFT(84),
  [108] = {.entry = {.count = 1, .reusable = true}}, SHIFT(87),
  [110] = {.entry = {.count = 1, .reusable = true}}, SHIFT(88),
  [112] = {.entry = {.count = 1, .reusable = true}}, SHIFT(89),
  [114] = {.entry = {.count = 1, .reusable = true}}, SHIFT(90),
  [116] = {.entry = {.count = 1, .reusable = true}}, SHIFT(91),
  [118] = {.entry = {.count = 1, .reusable = true}}, SHIFT(92),
  [120] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 1, 0, 0),
  [122] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 1, 0, 0),
  [124] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [126] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 3, 0, 0),
  [128] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 3, 0, 0),
  [130] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 3, 0, 0),
  [132] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_statement, 3, 0, 0),
  [134] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_statement, 3, 0, 0),
  [136] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 3, 0, 0),
  [138] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 3, 0, 0),
  [140] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_element, 3, 0, 0),
  [142] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_element, 3, 0, 0),
  [144] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_element, 3, 0, 0),
  [146] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_element, 3, 0, 0),
  [148] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_element, 3, 0, 0),
  [150] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_element, 3, 0, 0),
  [152] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wxs_element, 3, 0, 0),
  [154] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wxs_element, 3, 0, 0),
  [156] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [158] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_self_closing_tag, 4, 0, 0),
  [160] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_import_statement, 4, 0, 0),
  [162] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_import_statement, 4, 0, 0),
  [164] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_end_tag, 3, 0, 0),
  [166] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_end_tag, 3, 0, 0),
  [168] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_end_tag, 3, 0, 0),
  [170] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_end_tag, 3, 0, 0),
  [172] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_end_tag, 3, 0, 0),
  [174] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_end_tag, 3, 0, 0),
  [176] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_end_tag, 3, 0, 0),
  [178] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_end_tag, 3, 0, 0),
  [180] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wxs_end_tag, 3, 0, 0),
  [182] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wxs_end_tag, 3, 0, 0),
  [184] = {.entry = {.count = 1, .reusable = false}}, SHIFT(47),
  [186] = {.entry = {.count = 1, .reusable = false}}, SHIFT(99),
  [188] = {.entry = {.count = 1, .reusable = true}}, SHIFT(47),
  [190] = {.entry = {.count = 1, .reusable = true}}, SHIFT(26),
  [192] = {.entry = {.count = 1, .reusable = false}}, SHIFT(48),
  [194] = {.entry = {.count = 1, .reusable = true}}, SHIFT(48),
  [196] = {.entry = {.count = 1, .reusable = true}}, SHIFT(28),
  [198] = {.entry = {.count = 1, .reusable = false}}, SHIFT(49),
  [200] = {.entry = {.count = 1, .reusable = false}}, SHIFT(98),
  [202] = {.entry = {.count = 1, .reusable = true}}, SHIFT(49),
  [204] = {.entry = {.count = 1, .reusable = false}}, SHIFT(50),
  [206] = {.entry = {.count = 1, .reusable = true}}, SHIFT(50),
  [208] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [211] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0),
  [213] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(49),
  [216] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_attribute_value_repeat1, 2, 0, 0), SHIFT_REPEAT(26),
  [219] = {.entry = {.count = 2, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2, 0, 0), SHIFT_REPEAT(50),
  [222] = {.entry = {.count = 1, .reusable = false}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2, 0, 0),
  [224] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2, 0, 0), SHIFT_REPEAT(50),
  [227] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_quoted_attribute_value_repeat2, 2, 0, 0), SHIFT_REPEAT(28),
  [230] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_element, 2, 0, 0),
  [232] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_element, 2, 0, 0),
  [234] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 2, 0, 0),
  [236] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 2, 0, 0),
  [238] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_element, 2, 0, 0),
  [240] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_element, 2, 0, 0),
  [242] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_element, 2, 0, 0),
  [244] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_element, 2, 0, 0),
  [246] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wxs_element, 2, 0, 0),
  [248] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_wxs_element, 2, 0, 0),
  [250] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_element, 2, 0, 0),
  [252] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_element, 2, 0, 0),
  [254] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_interpolation, 3, 0, 1),
  [256] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_interpolation, 3, 0, 1),
  [258] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_include_statement, 4, 0, 0),
  [260] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_include_statement, 4, 0, 0),
  [262] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_start_tag, 3, 0, 0),
  [264] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_start_tag, 3, 0, 0),
  [266] = {.entry = {.count = 1, .reusable = true}}, SHIFT(66),
  [268] = {.entry = {.count = 1, .reusable = true}}, SHIFT(38),
  [270] = {.entry = {.count = 1, .reusable = true}}, SHIFT(82),
  [272] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 4, 0, 0),
  [274] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 4, 0, 0),
  [276] = {.entry = {.count = 1, .reusable = true}}, SHIFT(104),
  [278] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0),
  [280] = {.entry = {.count = 2, .reusable = true}}, REDUCE(aux_sym_start_tag_repeat1, 2, 0, 0), SHIFT_REPEAT(82),
  [283] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_start_tag, 4, 0, 0),
  [285] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_start_tag, 4, 0, 0),
  [287] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_start_tag, 4, 0, 0),
  [289] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_start_tag, 4, 0, 0),
  [291] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_block_start_tag, 4, 0, 0),
  [293] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_block_start_tag, 4, 0, 0),
  [295] = {.entry = {.count = 1, .reusable = true}}, SHIFT(77),
  [297] = {.entry = {.count = 1, .reusable = true}}, SHIFT(30),
  [299] = {.entry = {.count = 1, .reusable = true}}, SHIFT(61),
  [301] = {.entry = {.count = 1, .reusable = true}}, SHIFT(74),
  [303] = {.entry = {.count = 1, .reusable = true}}, SHIFT(71),
  [305] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_template_start_tag, 3, 0, 0),
  [307] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_template_start_tag, 3, 0, 0),
  [309] = {.entry = {.count = 1, .reusable = true}}, SHIFT(64),
  [311] = {.entry = {.count = 1, .reusable = true}}, SHIFT(59),
  [313] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_slot_start_tag, 3, 0, 0),
  [315] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_slot_start_tag, 3, 0, 0),
  [317] = {.entry = {.count = 1, .reusable = true}}, SHIFT(65),
  [319] = {.entry = {.count = 1, .reusable = true}}, SHIFT(105),
  [321] = {.entry = {.count = 1, .reusable = false}}, REDUCE(sym_start_tag, 3, 0, 0),
  [323] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_start_tag, 3, 0, 0),
  [325] = {.entry = {.count = 1, .reusable = true}}, SHIFT(39),
  [327] = {.entry = {.count = 1, .reusable = true}}, SHIFT(32),
  [329] = {.entry = {.count = 1, .reusable = true}}, SHIFT(58),
  [331] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 1, 0, 0),
  [333] = {.entry = {.count = 1, .reusable = true}}, SHIFT(94),
  [335] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__js_brace_expression, 2, 0, 0),
  [337] = {.entry = {.count = 1, .reusable = true}}, REDUCE(aux_sym__interpolation_text, 1, 0, 0),
  [339] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym__js_brace_expression, 3, 0, 0),
  [341] = {.entry = {.count = 1, .reusable = true}}, SHIFT(101),
  [343] = {.entry = {.count = 1, .reusable = true}}, SHIFT(45),
  [345] = {.entry = {.count = 1, .reusable = true}}, SHIFT(46),
  [347] = {.entry = {.count = 1, .reusable = true}}, SHIFT(31),
  [349] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 3, 0, 0),
  [351] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_quoted_attribute_value, 2, 0, 0),
  [353] = {.entry = {.count = 1, .reusable = true}}, SHIFT(113),
  [355] = {.entry = {.count = 1, .reusable = true}}, SHIFT(103),
  [357] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_attribute, 3, 0, 0),
  [359] = {.entry = {.count = 1, .reusable = true}}, SHIFT(110),
  [361] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wxs_start_tag, 4, 0, 0),
  [363] = {.entry = {.count = 1, .reusable = true}}, REDUCE(sym_wxs_start_tag, 3, 0, 0),
  [365] = {.entry = {.count = 1, .reusable = true}}, SHIFT(108),
  [367] = {.entry = {.count = 1, .reusable = true}}, SHIFT(42),
  [369] = {.entry = {.count = 1, .reusable = true}}, SHIFT(43),
  [371] = {.entry = {.count = 1, .reusable = true}}, SHIFT(44),
  [373] = {.entry = {.count = 1, .reusable = true}}, SHIFT(40),
  [375] = {.entry = {.count = 1, .reusable = true}}, SHIFT(115),
  [377] = {.entry = {.count = 1, .reusable = true}},  ACCEPT_INPUT(),
  [379] = {.entry = {.count = 1, .reusable = true}}, SHIFT(109),
  [381] = {.entry = {.count = 1, .reusable = true}}, SHIFT(107),
  [383] = {.entry = {.count = 1, .reusable = true}}, SHIFT(41),
};

enum ts_external_scanner_symbol_identifiers {
  ts_external_token__start_tag_name = 0,
  ts_external_token__end_tag_name = 1,
  ts_external_token_SLASH_GT = 2,
  ts_external_token_raw_text = 3,
  ts_external_token_comment = 4,
  ts_external_token__interpolation_start = 5,
  ts_external_token__interpolation_end = 6,
};

static const TSSymbol ts_external_scanner_symbol_map[EXTERNAL_TOKEN_COUNT] = {
  [ts_external_token__start_tag_name] = sym__start_tag_name,
  [ts_external_token__end_tag_name] = sym__end_tag_name,
  [ts_external_token_SLASH_GT] = anon_sym_SLASH_GT,
  [ts_external_token_raw_text] = sym_raw_text,
  [ts_external_token_comment] = sym_comment,
  [ts_external_token__interpolation_start] = sym__interpolation_start,
  [ts_external_token__interpolation_end] = sym__interpolation_end,
};

static const bool ts_external_scanner_states[9][EXTERNAL_TOKEN_COUNT] = {
  [1] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
    [ts_external_token__interpolation_start] = true,
    [ts_external_token__interpolation_end] = true,
  },
  [2] = {
    [ts_external_token_comment] = true,
    [ts_external_token__interpolation_start] = true,
  },
  [3] = {
    [ts_external_token_comment] = true,
    [ts_external_token__interpolation_start] = true,
    [ts_external_token__interpolation_end] = true,
  },
  [4] = {
    [ts_external_token__start_tag_name] = true,
    [ts_external_token_comment] = true,
  },
  [5] = {
    [ts_external_token_SLASH_GT] = true,
    [ts_external_token_comment] = true,
  },
  [6] = {
    [ts_external_token_comment] = true,
  },
  [7] = {
    [ts_external_token_raw_text] = true,
    [ts_external_token_comment] = true,
  },
  [8] = {
    [ts_external_token__end_tag_name] = true,
    [ts_external_token_comment] = true,
  },
};

#ifdef __cplusplus
extern "C" {
#endif
void *tree_sitter_wxml_external_scanner_create(void);
void tree_sitter_wxml_external_scanner_destroy(void *);
bool tree_sitter_wxml_external_scanner_scan(void *, TSLexer *, const bool *);
unsigned tree_sitter_wxml_external_scanner_serialize(void *, char *);
void tree_sitter_wxml_external_scanner_deserialize(void *, const char *, unsigned);

#ifdef TREE_SITTER_HIDE_SYMBOLS
#define TS_PUBLIC
#elif defined(_WIN32)
#define TS_PUBLIC __declspec(dllexport)
#else
#define TS_PUBLIC __attribute__((visibility("default")))
#endif

TS_PUBLIC const TSLanguage *tree_sitter_wxml(void) {
  static const TSLanguage language = {
    .abi_version = LANGUAGE_VERSION,
    .symbol_count = SYMBOL_COUNT,
    .alias_count = ALIAS_COUNT,
    .token_count = TOKEN_COUNT,
    .external_token_count = EXTERNAL_TOKEN_COUNT,
    .state_count = STATE_COUNT,
    .large_state_count = LARGE_STATE_COUNT,
    .production_id_count = PRODUCTION_ID_COUNT,
    .supertype_count = SUPERTYPE_COUNT,
    .field_count = FIELD_COUNT,
    .max_alias_sequence_length = MAX_ALIAS_SEQUENCE_LENGTH,
    .parse_table = &ts_parse_table[0][0],
    .small_parse_table = ts_small_parse_table,
    .small_parse_table_map = ts_small_parse_table_map,
    .parse_actions = ts_parse_actions,
    .symbol_names = ts_symbol_names,
    .symbol_metadata = ts_symbol_metadata,
    .public_symbol_map = ts_symbol_map,
    .alias_map = ts_non_terminal_alias_map,
    .alias_sequences = &ts_alias_sequences[0][0],
    .lex_modes = (const void*)ts_lex_modes,
    .lex_fn = ts_lex,
    .external_scanner = {
      &ts_external_scanner_states[0][0],
      ts_external_scanner_symbol_map,
      tree_sitter_wxml_external_scanner_create,
      tree_sitter_wxml_external_scanner_destroy,
      tree_sitter_wxml_external_scanner_scan,
      tree_sitter_wxml_external_scanner_serialize,
      tree_sitter_wxml_external_scanner_deserialize,
    },
    .primary_state_ids = ts_primary_state_ids,
    .name = "wxml",
    .max_reserved_word_set_size = 0,
    .metadata = {
      .major_version = 0,
      .minor_version = 1,
      .patch_version = 1,
    },
  };
  return &language;
}
#ifdef __cplusplus
}
#endif
